"""Application-service layer for RessourcePlanner.

This package exposes the stable transport-neutral application surface. NiceGUI today
and FastAPI later should depend on commands/results/facade rather than persistence or
historical implementation modules.
"""

from .allocation_service import AllocationService
from .business_contact_admin import (
    BusinessContactAdminRepositoryPort,
    BusinessContactAdminService,
    BusinessContactRecord,
    ContactLinkRecord,
    DemandOverrideMutationResult,
)
from .commands import (
    DemandAlternativeSelectCommand,
    DemandApproveCommand,
    DemandCancelCommand,
    DemandCorrectionCommand,
    DemandCreateCommand,
    DemandLineInput,
    DemandPeriodInput,
    DemandPeriodsReplaceCommand,
    DemandSubmitCommand,
    DemandUpdateCommand,
    ManualAllocationCreateCommand,
    ManualAllocationDeleteCommand,
    ManualAllocationMoveCommand,
    ManualAllocationReleaseCommand,
    ManualAllocationUpdateCommand,
    PlanningRebuildCommand,
    QuickShiftCreateCommand,
    SegmentAssignCommand,
    SegmentCancelCommand,
    SegmentCreateCommand,
    SegmentUpdateCommand,
    WorkPackageCreateCommand,
    WorkPackageUpdateCommand,
)
from .command_ports import (
    AllocationCommandPort,
    ApprovedDemandSyncPort,
    PlanningCommandPort,
)
from .competency_catalog import (
    CompetencyCatalogRepositoryPort,
    CompetencyCatalogService,
    CompetencyCreateCommand,
    CompetencyMutationResult,
    CompetencyReadModel,
    CompetencyUpdateCommand,
)
from .employee_sync import (
    EmployeeSourcePort,
    EmployeeSyncRepositoryPort,
    EmployeeSyncResult,
    EmployeeSyncService,
    ExternalEmployeeRecord,
)
from .errors import (
    ApplicationAuthorizationError,
    ApplicationConflictError,
    ApplicationError,
    ApplicationNotFoundError,
    ApplicationOperationError,
    ApplicationValidationError,
)
from .demand_workflow_policy import (
    ACTION_APPROVE,
    ACTION_CANCEL,
    ACTION_CORRECTION,
    ACTION_EMERGENCY_PLAN,
    ACTION_MODIFY,
    ACTION_SUBMIT,
    DemandWorkflowActionReadModel,
    DemandWorkflowBlock,
    DemandWorkflowReadModel,
    assert_demand_action,
    demand_workflow_state,
)
from .facade import ApplicationFacade
from .emergency_override import (
    DemandEmergencyOverrideCommand,
    EmergencyApplicationFacade,
    EmergencyDemandService,
    current_week_window,
    emergency_override_eligibility,
    emergency_window,
)
from .idempotency import (
    CommandIdempotencyPort,
    IdempotentCommandExecutor,
    normalize_idempotency_key,
    request_fingerprint,
)
from .identity_provisioning import (
    AutoProvisioningPolicy,
    IdentityProvisioningRepositoryPort,
    IdentityProvisioningService,
)
from .identity_resource_link import (
    IdentityResourceLinkRepositoryPort,
    IdentityResourceLinkService,
)
from .operational_contacts import (
    MaterializedContactContext,
    MaterializedContactResolution,
    OperationalContactRepositoryPort,
    OperationalContactService,
    RequestLineContactContext,
    RequestLineContactResolution,
)
from .plan_delta import DemandPlanDeltaItemReadModel, DemandPlanDeltaReadModel
from .project_communications import (
    ProjectCommunicationRepositoryPort,
    ProjectCommunicationService,
)
from .planning_service import PlanningService
from .project_sync import (
    ExternalProjectRecord,
    ProjectSourcePort,
    ProjectSyncRepositoryPort,
    ProjectSyncResult,
    ProjectSyncService,
)
from .query_models import (
    DemandHistoryReadModel,
    MediumTermUnlinkedSegmentReadModel,
    PendingDemandLoadReadModel,
    PlanningActionReadModel,
    PlanningCapacityGridReadModel,
    PlanningDayCapacityReadModel,
    PlanningResourceCapacityReadModel,
    PlanningSegmentCapacityDiagnosticReadModel,
    PlanningSnapshotReadModel,
    ProjectReadModel,
    ResourceAvailabilityRuleReadModel,
    ResourceReadModel,
    ResourceRecommendationReadModel,
    ShiftReadModel,
    WorkPackageReadModel,
)
from .query_ports import PlannerQueryPort
from .read_models import (
    DemandLineReadModel,
    DemandPeriodReadModel,
    DemandReadModel,
    SegmentMobilizedResourceReadModel,
    SegmentReadModel,
)
from .repository_ports import (
    DemandPeriodRepositoryPort,
    DemandRepositoryPort,
    PlanningReadRepositoryPort,
    SegmentRepositoryPort,
    WorkPackageRepositoryPort,
)
from .task_catalog import (
    TaskCatalogItem,
    TaskCatalogRepositoryPort,
    TaskCatalogSourcePort,
    TaskCatalogSyncResult,
    TaskCatalogSyncService,
)
from .resource_admin import (
    AVAILABILITY_HOLIDAY,
    AVAILABILITY_STANDARD,
    AVAILABILITY_TYPES,
    AVAILABILITY_VACATION,
    AvailabilityRuleCreateCommand,
    AvailabilityRuleMutationResult,
    AvailabilityRuleUpdateCommand,
    ResourceAdminRepositoryPort,
    ResourceAdminService,
    ResourceCreateCommand,
    ResourceMutationResult,
    ResourceUpdateCommand,
)
from .results import (
    AllocationMutationResult,
    ApplicationResult,
    DemandAlternativeSelectionResult,
    DemandMutationResult,
    DemandPeriodsMutationResult,
    PlanningResult,
    QuickShiftCreatedResult,
    SegmentMutationResult,
    WorkPackageMutationResult,
)
from .work_package_service import WorkPackageService

__all__ = [
    "AVAILABILITY_HOLIDAY",
    "AVAILABILITY_STANDARD",
    "AVAILABILITY_TYPES",
    "AVAILABILITY_VACATION",
    "AllocationCommandPort",
    "AllocationMutationResult",
    "AllocationService",
    "ApplicationAuthorizationError",
    "ApplicationConflictError",
    "ApplicationError",
    "ApplicationFacade",
    "ApplicationNotFoundError",
    "ApplicationOperationError",
    "ApplicationResult",
    "ApplicationValidationError",
    "ApprovedDemandSyncPort",
    "BusinessContactAdminRepositoryPort",
    "BusinessContactAdminService",
    "BusinessContactRecord",
    "AutoProvisioningPolicy",
    "AvailabilityRuleCreateCommand",
    "AvailabilityRuleMutationResult",
    "AvailabilityRuleUpdateCommand",
    "CompetencyCatalogRepositoryPort",
    "CompetencyCatalogService",
    "CompetencyCreateCommand",
    "CompetencyMutationResult",
    "CompetencyReadModel",
    "CompetencyUpdateCommand",
    "CommandIdempotencyPort",
    "ContactLinkRecord",
    "DemandAlternativeSelectCommand",
    "DemandAlternativeSelectionResult",
    "DemandApproveCommand",
    "DemandCancelCommand",
    "DemandCorrectionCommand",
    "DemandCreateCommand",
    "DemandLineInput",
    "DemandEmergencyOverrideCommand",
    "DemandHistoryReadModel",
    "DemandLineReadModel",
    "DemandMutationResult",
    "DemandOverrideMutationResult",
    "DemandPeriodInput",
    "DemandPeriodReadModel",
    "DemandPeriodRepositoryPort",
    "DemandPeriodsMutationResult",
    "DemandPeriodsReplaceCommand",
    "DemandPlanDeltaItemReadModel",
    "DemandPlanDeltaReadModel",
    "DemandReadModel",
    "DemandRepositoryPort",
    "DemandSubmitCommand",
    "DemandUpdateCommand",
    "EmergencyApplicationFacade",
    "EmergencyDemandService",
    "EmployeeSourcePort",
    "EmployeeSyncRepositoryPort",
    "EmployeeSyncResult",
    "EmployeeSyncService",
    "ExternalEmployeeRecord",
    "ExternalProjectRecord",
    "IdentityProvisioningRepositoryPort",
    "IdentityProvisioningService",
    "IdentityResourceLinkRepositoryPort",
    "IdentityResourceLinkService",
    "IdempotentCommandExecutor",
    "ManualAllocationCreateCommand",
    "ManualAllocationDeleteCommand",
    "ManualAllocationMoveCommand",
    "ManualAllocationReleaseCommand",
    "ManualAllocationUpdateCommand",
    "MaterializedContactContext",
    "MaterializedContactResolution",
    "MediumTermUnlinkedSegmentReadModel",
    "PendingDemandLoadReadModel",
    "OperationalContactRepositoryPort",
    "OperationalContactService",
    "PlanningActionReadModel",
    "PlanningCapacityGridReadModel",
    "PlanningDayCapacityReadModel",
    "PlanningResourceCapacityReadModel",
    "PlanningSegmentCapacityDiagnosticReadModel",
    "PlannerQueryPort",
    "PlanningCommandPort",
    "PlanningReadRepositoryPort",
    "PlanningRebuildCommand",
    "PlanningResult",
    "PlanningService",
    "PlanningSnapshotReadModel",
    "ProjectCommunicationRepositoryPort",
    "ProjectCommunicationService",
    "ProjectReadModel",
    "ProjectSourcePort",
    "ProjectSyncRepositoryPort",
    "ProjectSyncResult",
    "ProjectSyncService",
    "QuickShiftCreateCommand",
    "QuickShiftCreatedResult",
    "RequestLineContactContext",
    "RequestLineContactResolution",
    "ResourceAdminRepositoryPort",
    "ResourceAdminService",
    "ResourceAvailabilityRuleReadModel",
    "ResourceCreateCommand",
    "ResourceMutationResult",
    "ResourceReadModel",
    "ResourceRecommendationReadModel",
    "ResourceUpdateCommand",
    "SegmentAssignCommand",
    "SegmentCancelCommand",
    "SegmentCreateCommand",
    "SegmentMutationResult",
    "SegmentMobilizedResourceReadModel",
    "SegmentReadModel",
    "SegmentRepositoryPort",
    "SegmentUpdateCommand",
    "ShiftReadModel",
    "WorkPackageCreateCommand",
    "TaskCatalogItem",
    "TaskCatalogRepositoryPort",
    "TaskCatalogSourcePort",
    "TaskCatalogSyncResult",
    "TaskCatalogSyncService",
    "WorkPackageMutationResult",
    "WorkPackageReadModel",
    "WorkPackageRepositoryPort",
    "WorkPackageService",
    "WorkPackageUpdateCommand",
    "current_week_window",
    "emergency_override_eligibility",
    "emergency_window",
    "normalize_idempotency_key",
    "request_fingerprint",
]