"""Application-service layer for RessourcePlanner.

This package exposes the stable transport-neutral application surface. NiceGUI today
and FastAPI later should depend on commands/results/facade rather than persistence or
historical implementation modules.
"""

from .allocation_service import AllocationService
from .commands import (
    DemandAlternativeSelectCommand,
    DemandApproveCommand,
    DemandCancelCommand,
    DemandCorrectionCommand,
    DemandCreateCommand,
    DemandPeriodInput,
    DemandPeriodsReplaceCommand,
    DemandSubmitCommand,
    DemandUpdateCommand,
    ManualAllocationCreateCommand,
    ManualAllocationDeleteCommand,
    ManualAllocationReleaseCommand,
    ManualAllocationUpdateCommand,
    PlanningRebuildCommand,
    QuickShiftCreateCommand,
    SegmentAssignCommand,
    SegmentCancelCommand,
    SegmentCreateCommand,
    SegmentUpdateCommand,
    WorkPackageCreateCommand,
    WorkPackageUpdateCommand,
)
from .command_ports import (
    AllocationCommandPort,
    ApprovedDemandSyncPort,
    PlanningCommandPort,
)
from .employee_sync import (
    EmployeeSourcePort,
    EmployeeSyncRepositoryPort,
    EmployeeSyncResult,
    EmployeeSyncService,
    ExternalEmployeeRecord,
)
from .errors import (
    ApplicationConflictError,
    ApplicationError,
    ApplicationNotFoundError,
    ApplicationOperationError,
    ApplicationValidationError,
)
from .facade import ApplicationFacade
from .idempotency import (
    CommandIdempotencyPort,
    IdempotentCommandExecutor,
    normalize_idempotency_key,
    request_fingerprint,
)
from .identity_provisioning import (
    AutoProvisioningPolicy,
    IdentityProvisioningRepositoryPort,
    IdentityProvisioningService,
)
from .identity_resource_link import (
    IdentityResourceLinkRepositoryPort,
    IdentityResourceLinkService,
)
from .planning_service import PlanningService
from .project_sync import (
    ExternalProjectRecord,
    ProjectSourcePort,
    ProjectSyncRepositoryPort,
    ProjectSyncResult,
    ProjectSyncService,
)
from .query_models import (
    DemandHistoryReadModel,
    PendingDemandLoadReadModel,
    PlanningSnapshotReadModel,
    ProjectReadModel,
    ResourceAvailabilityRuleReadModel,
    ResourceReadModel,
    ShiftReadModel,
    WorkPackageReadModel,
)
from .query_ports import PlannerQueryPort
from .read_models import DemandPeriodReadModel, DemandReadModel, SegmentReadModel
from .repository_ports import (
    DemandPeriodRepositoryPort,
    DemandRepositoryPort,
    PlanningReadRepositoryPort,
    SegmentRepositoryPort,
    WorkPackageRepositoryPort,
)
from .resource_admin import (
    AVAILABILITY_HOLIDAY,
    AVAILABILITY_STANDARD,
    AVAILABILITY_TYPES,
    AVAILABILITY_VACATION,
    AvailabilityRuleCreateCommand,
    AvailabilityRuleMutationResult,
    AvailabilityRuleUpdateCommand,
    ResourceAdminRepositoryPort,
    ResourceAdminService,
    ResourceCreateCommand,
    ResourceMutationResult,
    ResourceUpdateCommand,
)
from .results import (
    AllocationMutationResult,
    ApplicationResult,
    DemandAlternativeSelectionResult,
    DemandMutationResult,
    DemandPeriodsMutationResult,
    PlanningResult,
    QuickShiftCreatedResult,
    SegmentMutationResult,
    WorkPackageMutationResult,
)
from .work_package_service import WorkPackageService

__all__ = [
    "AVAILABILITY_HOLIDAY",
    "AVAILABILITY_STANDARD",
    "AVAILABILITY_TYPES",
    "AVAILABILITY_VACATION",
    "AllocationCommandPort",
    "AllocationMutationResult",
    "AllocationService",
    "ApplicationConflictError",
    "ApplicationError",
    "ApplicationFacade",
    "ApplicationNotFoundError",
    "ApplicationOperationError",
    "ApplicationResult",
    "ApplicationValidationError",
    "ApprovedDemandSyncPort",
    "AutoProvisioningPolicy",
    "AvailabilityRuleCreateCommand",
    "AvailabilityRuleMutationResult",
    "AvailabilityRuleUpdateCommand",
    "CommandIdempotencyPort",
    "DemandAlternativeSelectCommand",
    "DemandAlternativeSelectionResult",
    "DemandApproveCommand",
    "DemandCancelCommand",
    "DemandCorrectionCommand",
    "DemandCreateCommand",
    "DemandHistoryReadModel",
    "DemandMutationResult",
    "DemandPeriodInput",
    "DemandPeriodReadModel",
    "DemandPeriodRepositoryPort",
    "DemandPeriodsMutationResult",
    "DemandPeriodsReplaceCommand",
    "DemandReadModel",
    "DemandRepositoryPort",
    "DemandSubmitCommand",
    "DemandUpdateCommand",
    "EmployeeSourcePort",
    "EmployeeSyncRepositoryPort",
    "EmployeeSyncResult",
    "EmployeeSyncService",
    "ExternalEmployeeRecord",
    "ExternalProjectRecord",
    "IdentityProvisioningRepositoryPort",
    "IdentityProvisioningService",
    "IdentityResourceLinkRepositoryPort",
    "IdentityResourceLinkService",
    "IdempotentCommandExecutor",
    "ManualAllocationCreateCommand",
    "ManualAllocationDeleteCommand",
    "ManualAllocationReleaseCommand",
    "ManualAllocationUpdateCommand",
    "PendingDemandLoadReadModel",
    "PlannerQueryPort",
    "PlanningCommandPort",
    "PlanningReadRepositoryPort",
    "PlanningRebuildCommand",
    "PlanningResult",
    "PlanningService",
    "PlanningSnapshotReadModel",
    "ProjectReadModel",
    "ProjectSourcePort",
    "ProjectSyncRepositoryPort",
    "ProjectSyncResult",
    "ProjectSyncService",
    "QuickShiftCreateCommand",
    "QuickShiftCreatedResult",
    "ResourceAdminRepositoryPort",
    "ResourceAdminService",
    "ResourceAvailabilityRuleReadModel",
    "ResourceCreateCommand",
    "ResourceMutationResult",
    "ResourceReadModel",
    "ResourceUpdateCommand",
    "SegmentAssignCommand",
    "SegmentCancelCommand",
    "SegmentCreateCommand",
    "SegmentMutationResult",
    "SegmentReadModel",
    "SegmentRepositoryPort",
    "SegmentUpdateCommand",
    "ShiftReadModel",
    "WorkPackageCreateCommand",
    "WorkPackageMutationResult",
    "WorkPackageReadModel",
    "WorkPackageRepositoryPort",
    "WorkPackageService",
    "WorkPackageUpdateCommand",
    "normalize_idempotency_key",
    "request_fingerprint",
]
