"""add reservable asset models

Revision ID: 0036_reservable_assets
Revises: 0035_global_planning_version
Create Date: 2026-09-23 09:27:41.689771
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0036_reservable_assets'
down_revision: Union[str, Sequence[str], None] = '0035_global_planning_version'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_types',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('occupancy_policy', sa.String(length=32), server_default=sa.text("'EXCLUSIVE_DAY'"), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_types')),
    sa.UniqueConstraint('code', name='uq_asset_types_code')
    )
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('asset_type_id', sa.String(length=36), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_types.id'], name=op.f('fk_assets_asset_type_id_asset_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets')),
    sa.UniqueConstraint('code', name='uq_assets_code')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_asset_type_id'), ['asset_type_id'], unique=False)

    op.create_table('asset_unavailability',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_asset_unavailability_asset_unavailability_window')),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_unavailability_asset_id_assets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_unavailability'))
    )
    with op.batch_alter_table('asset_unavailability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_unavailability_asset_id'), ['asset_id'], unique=False)

    op.create_table('asset_requirements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('workforce_request_id', sa.String(length=36), nullable=False),
    sa.Column('source_request_line_id', sa.String(length=36), nullable=False),
    sa.Column('source_period_id', sa.String(length=36), nullable=True),
    sa.Column('approval_revision_id', sa.String(length=36), nullable=True),
    sa.Column('approved_entry_key', sa.String(length=512), nullable=False),
    sa.Column('slot_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('asset_type_id', sa.String(length=36), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('usage_hours', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'À affecter'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_asset_requirements_asset_requirement_window')),
    sa.CheckConstraint('usage_hours IS NULL OR usage_hours > 0', name=op.f('ck_asset_requirements_asset_requirement_hours_positive')),
    sa.ForeignKeyConstraint(['approval_revision_id'], ['request_approval_revisions.id'], name=op.f('fk_asset_requirements_approval_revision_id_request_approval_revisions')),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_types.id'], name=op.f('fk_asset_requirements_asset_type_id_asset_types')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_asset_requirements_project_id_projects')),
    sa.ForeignKeyConstraint(['source_period_id'], ['workforce_request_periods.id'], name=op.f('fk_asset_requirements_source_period_id_workforce_request_periods')),
    sa.ForeignKeyConstraint(['source_request_line_id'], ['request_lines.id'], name=op.f('fk_asset_requirements_source_request_line_id_request_lines')),
    sa.ForeignKeyConstraint(['workforce_request_id'], ['workforce_requests.id'], name=op.f('fk_asset_requirements_workforce_request_id_workforce_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_requirements')),
    sa.UniqueConstraint('workforce_request_id', 'approved_entry_key', 'slot_index', name='uq_asset_requirement_entry_slot')
    )
    with op.batch_alter_table('asset_requirements', schema=None) as batch_op:
        batch_op.create_index('ix_asset_requirements_request', ['workforce_request_id', 'source_request_line_id'], unique=False)

    op.create_table('asset_allocations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_requirement_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('locked', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('source', sa.String(length=32), server_default=sa.text("'MANUAL'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_asset_allocations_asset_allocation_window')),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_allocations_asset_id_assets')),
    sa.ForeignKeyConstraint(['asset_requirement_id'], ['asset_requirements.id'], name=op.f('fk_asset_allocations_asset_requirement_id_asset_requirements')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_allocations')),
    sa.UniqueConstraint('asset_requirement_id', name='uq_asset_allocation_requirement')
    )
    with op.batch_alter_table('asset_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_allocations_asset_requirement_id'), ['asset_requirement_id'], unique=False)
        batch_op.create_index('ix_asset_allocations_asset_window', ['asset_id', 'start_date', 'end_date'], unique=False)

    with op.batch_alter_table('request_lines') as batch_op:
        batch_op.add_column(sa.Column('asset_type_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('proposed_asset_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_request_lines_asset_type_id_asset_types', 'asset_types', ['asset_type_id'], ['id'])
        batch_op.create_foreign_key('fk_request_lines_proposed_asset_id_assets', 'assets', ['proposed_asset_id'], ['id'])
        batch_op.create_index('ix_request_lines_asset_type_id', ['asset_type_id'])
        batch_op.create_index('ix_request_lines_proposed_asset_id', ['proposed_asset_id'])

    with op.batch_alter_table('workforce_request_periods') as batch_op:
        batch_op.alter_column('hours', existing_type=sa.Numeric(12, 2), nullable=True)
        batch_op.drop_constraint(batch_op.f('ck_workforce_request_periods_request_period_hours_positive'), type_='check')
        batch_op.create_check_constraint(batch_op.f('ck_workforce_request_periods_request_period_hours_positive'), 'hours IS NULL OR hours > 0')

    # ### end Alembic commands ###


def downgrade() -> None:
    with op.batch_alter_table('workforce_request_periods') as batch_op:
        batch_op.drop_constraint(batch_op.f('ck_workforce_request_periods_request_period_hours_positive'), type_='check')
        batch_op.create_check_constraint(batch_op.f('ck_workforce_request_periods_request_period_hours_positive'), 'hours > 0')
        batch_op.alter_column('hours', existing_type=sa.Numeric(12, 2), nullable=False)
    with op.batch_alter_table('request_lines') as batch_op:
        batch_op.drop_index('ix_request_lines_proposed_asset_id')
        batch_op.drop_index('ix_request_lines_asset_type_id')
        batch_op.drop_constraint('fk_request_lines_proposed_asset_id_assets', type_='foreignkey')
        batch_op.drop_constraint('fk_request_lines_asset_type_id_asset_types', type_='foreignkey')
        batch_op.drop_column('proposed_asset_id')
        batch_op.drop_column('asset_type_id')

    with op.batch_alter_table('asset_allocations', schema=None) as batch_op:
        batch_op.drop_index('ix_asset_allocations_asset_window')
        batch_op.drop_index(batch_op.f('ix_asset_allocations_asset_requirement_id'))

    op.drop_table('asset_allocations')
    with op.batch_alter_table('asset_requirements', schema=None) as batch_op:
        batch_op.drop_index('ix_asset_requirements_request')

    op.drop_table('asset_requirements')
    with op.batch_alter_table('asset_unavailability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_unavailability_asset_id'))

    op.drop_table('asset_unavailability')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_asset_type_id'))

    op.drop_table('assets')
    op.drop_table('asset_types')
    # ### end Alembic commands ###
