"""Add persistent approval cycles and submission snapshots.

Revision ID: 0040_approval_cycles
Revises: 0039_approval_scopes
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "0040_approval_cycles"
down_revision: Union[str, Sequence[str], None] = "0039_approval_scopes"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

ID_LENGTH = 36


def upgrade() -> None:
    op.create_table(
        "request_approval_cycles",
        sa.Column("id", sa.String(length=ID_LENGTH), nullable=False),
        sa.Column(
            "workforce_request_id",
            sa.String(length=ID_LENGTH),
            nullable=False,
        ),
        sa.Column(
            "submitted_request_version",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.String(length=32),
            server_default=sa.text("'OPEN'"),
            nullable=False,
        ),
        sa.Column(
            "subject_fingerprint",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "initialization_reason",
            sa.String(length=32),
            server_default=sa.text("'SUBMISSION'"),
            nullable=False,
        ),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "invalidated_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "invalidation_reason",
            sa.String(length=128),
            nullable=True,
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "approved_revision_id",
            sa.String(length=ID_LENGTH),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "submitted_request_version >= 1",
            name="ck_appr_cycle_request_version",
        ),
        sa.CheckConstraint(
            "state IN ('OPEN','INVALIDATED','COMPLETED')",
            name="ck_appr_cycle_state",
        ),
        sa.ForeignKeyConstraint(
            ["workforce_request_id"],
            ["workforce_requests.id"],
            name="fk_appr_cycle_request",
        ),
        sa.ForeignKeyConstraint(
            ["approved_revision_id"],
            ["request_approval_revisions.id"],
            name="fk_appr_cycle_revision",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_request_approval_cycles",
        ),
    )
    op.create_index(
        "ix_request_approval_cycles_workforce_request_id",
        "request_approval_cycles",
        ["workforce_request_id"],
        unique=False,
    )
    op.create_index(
        "ix_request_approval_cycles_state",
        "request_approval_cycles",
        ["state"],
        unique=False,
    )
    op.create_index(
        "ix_request_approval_cycles_subject_fingerprint",
        "request_approval_cycles",
        ["subject_fingerprint"],
        unique=False,
    )
    op.create_index(
        "ix_request_approval_cycles_approved_revision_id",
        "request_approval_cycles",
        ["approved_revision_id"],
        unique=False,
    )
    op.create_index(
        "ix_request_approval_cycles_request_state",
        "request_approval_cycles",
        ["workforce_request_id", "state"],
        unique=False,
    )

    op.create_table(
        "approval_requirements",
        sa.Column("id", sa.String(length=ID_LENGTH), nullable=False),
        sa.Column(
            "approval_cycle_id",
            sa.String(length=ID_LENGTH),
            nullable=False,
        ),
        sa.Column(
            "request_line_id",
            sa.String(length=ID_LENGTH),
            nullable=False,
        ),
        sa.Column(
            "task_catalog_item_id",
            sa.String(length=ID_LENGTH),
            nullable=True,
        ),
        sa.Column(
            "approval_scope_id",
            sa.String(length=ID_LENGTH),
            nullable=True,
        ),
        sa.Column(
            "proposed_resource_id",
            sa.String(length=ID_LENGTH),
            nullable=True,
        ),
        sa.Column(
            "routing_sources_text",
            sa.Text(),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approval_cycle_id"],
            ["request_approval_cycles.id"],
            name="fk_appr_requirement_cycle",
        ),
        sa.ForeignKeyConstraint(
            ["request_line_id"],
            ["request_lines.id"],
            name="fk_appr_requirement_line",
        ),
        sa.ForeignKeyConstraint(
            ["task_catalog_item_id"],
            ["task_catalog_items.id"],
            name="fk_appr_requirement_task",
        ),
        sa.ForeignKeyConstraint(
            ["approval_scope_id"],
            ["approval_scopes.id"],
            name="fk_appr_requirement_scope",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_resource_id"],
            ["resources.id"],
            name="fk_appr_requirement_resource",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_approval_requirements",
        ),
        sa.UniqueConstraint(
            "approval_cycle_id",
            "request_line_id",
            name="uq_approval_requirement_cycle_line",
        ),
    )
    op.create_index(
        "ix_approval_requirements_cycle",
        "approval_requirements",
        ["approval_cycle_id"],
        unique=False,
    )
    op.create_index(
        "ix_approval_requirements_request_line_id",
        "approval_requirements",
        ["request_line_id"],
        unique=False,
    )
    op.create_index(
        "ix_approval_requirements_task_catalog_item_id",
        "approval_requirements",
        ["task_catalog_item_id"],
        unique=False,
    )
    op.create_index(
        "ix_approval_requirements_approval_scope_id",
        "approval_requirements",
        ["approval_scope_id"],
        unique=False,
    )
    op.create_index(
        "ix_approval_requirements_proposed_resource_id",
        "approval_requirements",
        ["proposed_resource_id"],
        unique=False,
    )

    op.create_table(
        "approval_requirement_approvers",
        sa.Column(
            "requirement_id",
            sa.String(length=ID_LENGTH),
            nullable=False,
        ),
        sa.Column(
            "app_user_id",
            sa.String(length=ID_LENGTH),
            nullable=False,
        ),
        sa.Column(
            "sources_text",
            sa.Text(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["approval_requirements.id"],
            name="fk_appr_req_approver_requirement",
        ),
        sa.ForeignKeyConstraint(
            ["app_user_id"],
            ["app_users.id"],
            name="fk_appr_req_approver_user",
        ),
        sa.PrimaryKeyConstraint(
            "requirement_id",
            "app_user_id",
            name="pk_approval_requirement_approvers",
        ),
    )
    op.create_index(
        "ix_approval_requirement_approvers_user",
        "approval_requirement_approvers",
        ["app_user_id"],
        unique=False,
    )

    op.create_table(
        "approval_decisions",
        sa.Column("id", sa.String(length=ID_LENGTH), nullable=False),
        sa.Column(
            "requirement_id",
            sa.String(length=ID_LENGTH),
            nullable=False,
        ),
        sa.Column(
            "app_user_id",
            sa.String(length=ID_LENGTH),
            nullable=False,
        ),
        sa.Column(
            "decision",
            sa.String(length=32),
            nullable=False,
        ),
        sa.Column(
            "decided_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "action_id",
            sa.String(length=ID_LENGTH),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["approval_requirements.id"],
            name="fk_approval_decision_requirement",
        ),
        sa.ForeignKeyConstraint(
            ["app_user_id"],
            ["app_users.id"],
            name="fk_approval_decision_user",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_approval_decisions",
        ),
    )
    op.create_index(
        "ix_approval_decisions_requirement_actor",
        "approval_decisions",
        ["requirement_id", "app_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_approval_decisions_action",
        "approval_decisions",
        ["action_id"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        "ix_approval_decisions_action",
        table_name="approval_decisions",
    )
    op.drop_index(
        "ix_approval_decisions_requirement_actor",
        table_name="approval_decisions",
    )
    op.drop_table("approval_decisions")

    op.drop_index(
        "ix_approval_requirement_approvers_user",
        table_name="approval_requirement_approvers",
    )
    op.drop_table("approval_requirement_approvers")

    op.drop_index(
        "ix_approval_requirements_proposed_resource_id",
        table_name="approval_requirements",
    )
    op.drop_index(
        "ix_approval_requirements_approval_scope_id",
        table_name="approval_requirements",
    )
    op.drop_index(
        "ix_approval_requirements_task_catalog_item_id",
        table_name="approval_requirements",
    )
    op.drop_index(
        "ix_approval_requirements_request_line_id",
        table_name="approval_requirements",
    )
    op.drop_index(
        "ix_approval_requirements_cycle",
        table_name="approval_requirements",
    )
    op.drop_table("approval_requirements")

    op.drop_index(
        "ix_request_approval_cycles_request_state",
        table_name="request_approval_cycles",
    )
    op.drop_index(
        "ix_request_approval_cycles_approved_revision_id",
        table_name="request_approval_cycles",
    )
    op.drop_index(
        "ix_request_approval_cycles_subject_fingerprint",
        table_name="request_approval_cycles",
    )
    op.drop_index(
        "ix_request_approval_cycles_state",
        table_name="request_approval_cycles",
    )
    op.drop_index(
        "ix_request_approval_cycles_workforce_request_id",
        table_name="request_approval_cycles",
    )
    op.drop_table("request_approval_cycles")
